### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by lhyfst** [MCG-NJU/SADRNet#16]
When I train the model from scratch, sometimes I encounter such an error:
```
$ python src/run/train_block_data.py
Namespace(visible_device='0')
True 4 0 GeForce GTX 1080
loading data path list
data path list loaded
2000 data added
Epoch: 0
[epoch:0,block:0/200, iter:39/38, time:41] loss: 4.39420 offset_uvm: 0.13145 face_uvm: 0.00000 kpt_uvm: 4.22837 attention_mask: 0.02870 edge: 0.00101 norm: 0.00467 
val_offset_uvm: 0.05806 val_face_uvm: 0.83816 val_kpt_uvm: 1.05301 val_attention_mask: 0.39309 125  
new best 2.3423 improved from 100000.0000
Epoch: 1
[epoch:1,block:0/200, iter:39/38, time:25] loss: 2.14687 offset_uvm: 0.13437 face_uvm: 0.00000 kpt_uvm: 1.98520 attention_mask: 0.02144 edge: 0.00104 norm: 0.00483 
val_offset_uvm: 0.05771 val_face_uvm: 0.42581 val_kpt_uvm: 0.45449 val_attention_mask: 0.24950 125  
new best 1.1875 improved from 2.3423
Epoch: 2
[epoch:2,block:0/200, iter:39/38, time:26] loss: 1.72705 offset_uvm: 0.13805 face_uvm: 0.00000 kpt_uvm: 1.56464 attention_mask: 0.01831 edge: 0.00106 norm: 0.00500 
/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "src/run/train_block_data.py", line 346, in <module>
    trainer.train()
  File "src/run/train_block_data.py", line 281, in train
    'eval')
  File "/home/heyuan/Environments/anaconda3/envs/SADRNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/heyuan/Research/3d_face/SADRNet/src/model/SADRNv2.py", line 128, in forward
    face_uvm = self.rebuilder(offset_uvm, kpt_uvm,attention)
  File "/home/heyuan/Environments/anaconda3/envs/SADRNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/heyuan/Research/3d_face/SADRNet/src/model/modules.py", line 374, in forward
    [attention[i, 0, kpt_ind[i, :, 1] // 8, kpt_ind[i, :, 0] // 8] for i in range(B)])
  File "/home/heyuan/Research/3d_face/SADRNet/src/model/modules.py", line 374, in <listcomp>
    [attention[i, 0, kpt_ind[i, :, 1] // 8, kpt_ind[i, :, 0] // 8] for i in range(B)])
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by xhlbetter** [comment]
same question

**Comment by xhlbetter** [comment]
Hi, how did you solve this issue? I am running into the same problem and not sure what the solution is.

**Comment by xhlbetter** [comment]
![image](https://github.com/MCG-NJU/SADRNet/assets/105650177/863f3851-8073-45b6-8d78-d5f1fd6bd67a)

**Comment by SFyingchen** [comment]
Hi, how did you solve this issue?  @xhlbetter ， I have  the  same question
