### ISSUE TITLE
ImportError: cannot import name 'uv_triangles'

### ISSUE THREAD

**Issue by HeBangYan** [MCG-NJU/SADRNet#20]
When I run the `python src/run/train_block_data.py` command, the following error is reported. How can I solve it?

note: UV_TRIANGLES_PATH = '../data/uv_data/uv_triangles.npy' exists.

```
Traceback (most recent call last):
  File "src/run/train_block_data.py", line 343, in <module>
    trainer = SADRNv2Trainer()
  File "src/run/train_block_data.py", line 319, in __init__
    super(SADRNTrainer, self).__init__()
  File "src/run/train_block_data.py", line 122, in __init__
    self.model = self.get_model()
  File "src/run/train_block_data.py", line 325, in get_model
    from src.model.SADRNv2 import get_model
  File "/media/bangyanhe/disk/SADRNet-main/src/model/SADRNv2.py", line 2, in <module>
    from src.model.loss import *
  File "/media/bangyanhe/disk/SADRNet-main/src/model/loss.py", line 7, in <module>
    from src.dataset.uv_face import face_mask_np, face_mask_fix_rate, foreface_ind, uv_kpt_ind, uv_edges, uv_triangles
ImportError: cannot import name 'uv_triangles'
```

**Comment by reshow** [comment]
This issue can help you [https://github.com/MCG-NJU/SADRNet/issues/2 ](https://github.com/MCG-NJU/SADRNet/issues/2 ) .
