### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jackweiwang** [MCG-NJU/SADRNet#9]
When i predict 1.jpg I get 1_info.mat , how was this file generated? thanks 

```txt

dirs= ['1']
Traceback (most recent call last):
  File "/root/anaconda/envs/ai/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 33, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/root/filters/SADRNet/data/example/1/1_info.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/run/predict.py", line 245, in <module>
    evaluator.get_example_data()
  File "src/run/predict.py", line 105, in get_example_data
    val_dataset = make_dataset(['/root/filters/SADRNet/data/example'], 'val')
  File "./src/dataset/dataloader.py", line 219, in make_dataset
    raw_dataset.add_image_data(folder, mode)
  File "./src/dataset/dataloader.py", line 97, in add_image_data
    temp_image_data.read_path(root + '/' + dir_name)
  File "./src/dataset/dataloader.py", line 40, in read_path
    info = sio.loadmat(self.info_path)
  File "/root/anaconda/envs/ai/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/root/anaconda/envs/ai/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/root/anaconda/envs/ai/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/root/filters/SADRNet/data/example/1/1_info.mat'

```

**Comment by jackweiwang** [comment]
> This is probably because of the PyTorch version. I tested PyTorch 1.6.0 and had this problem too. Maybe you should try PyTorch 1.2.0.

Solved, thank you.

**Comment by 1winter996** [comment]
How was the final solution?Is it the Pytorch version? I changed the Pytorch==1.2 version with the same problem，Looking forward to your reply, thank you.

**Comment by NewtOliver** [comment]
I am using CUDA version 11.3, which is incompatible with PyTorch 1.2.0. Are there any other solutions？
